name: Android CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/checkout@v4
      - name: Copy Google Services Json File
        uses: canastro/copy-file-action@master
        with:
          source: "google-services-for-ci.json"
          target: "app/google-services.json"
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
