name: Android CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Copy Google Services Json File
        run: cp google-services-for-ci.json app/google-services.json

      - name: Build and Test
        run: ./gradlew lintDebug testDebugUnitTest assembleDebug
