name: Android CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/checkout@master
    - name: Copy Google Services Json File
      uses: canastro/copy-file-action@master
      with:
        source: "google-services-for-ci.json"
        target: "app/google-services.json"
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest
