name: Publish APK to PlayStore

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo "$FIREBASE_CONFIG" > app/google-services.json

      - name: Decode service account key
        env:
          SERVICE_ACCOUNT: ${{ secrets.PLAY_STORE_JSON }}
        run: echo "$SERVICE_ACCOUNT" > play_store_secret.json

      - name: Publish and Build
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease publishBundle

      - name: Save APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: warn

      - name: Save Bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: app/build/outputs/bundle/release/app-release.aab
          if-no-files-found: warn
