name: Publish APK to PlayStore

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 21
        uses: actions/setup-java@v3.14.1
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json

      - name: Decode service account key
        env:
          SERVICE_ACCOUNT: ${{ secrets.PLAY_STORE_JSON }}
        run: echo $SERVICE_ACCOUNT > play_store_secret.json

      - name: Publish APK
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew assemble publishBundle

      - name: Save artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: app/build/intermidiates/apk/release/app-release.apk
          if-no-files-found: ignore
